server:
  port: 8081
  address: localhost
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mlh_db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mlh
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      min-idle: 1   #最小连接数
      max-active: 8  #最大连接数（默认为8）
      max-wait: 1000  #获取连接时的最大等待时间
      min-evictable-idle-time-millis: 300000   #一个连接池在池中最小生存的时间，毫秒
      time-between-eviction-runs-millis: 60000   #多久才进行一次检测需要关闭的空闲连接，单位是毫秒
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl